### ISSUE TITLE
How to use my own spectral dataset?

### ISSUE THREAD

**Issue by Turingic** [NISL-MSU/HSI-BandSelection#4]
Hello! When I try to do the band selection on my own dataset, it keeps reporting the error in the image. I tried to change the code but none of it worked. The size of my own spectral dataset is 1920x1080x29.
<img width="1246" alt="image" src="https://github.com/NISL-MSU/HSI-BandSelection/assets/167987012/f5f52c8b-57e3-402b-9273-99f6a9e1d84f">
<img width="1051" alt="image" src="https://github.com/NISL-MSU/HSI-BandSelection/assets/167987012/247bbf43-b14d-44c7-8ad1-e1d332808e9a">

**Comment by Turingic** [comment]
When I change the runtime from GPU to CPU, the error is like this:
<img width="1177" alt="image" src="https://github.com/NISL-MSU/HSI-BandSelection/assets/167987012/78da9c87-34e7-40a2-aef1-d7873e385f12">
<img width="1182" alt="image" src="https://github.com/NISL-MSU/HSI-BandSelection/assets/167987012/0769a0cb-b3c5-4ab3-ae54-05091bf67309">

**Comment by GiorgioMorales** [comment]
Hi! The first error is because you don't have a correct Pytorch+CUDA installation. The second error seems to be related to the dimensions of your dataset. Use our [demo](https://colab.research.google.com/github/NISL-MSU/HSI-BandSelection/blob/master/HSIBandSelection.ipynb#scrollTo=D-Hgf37-VG98) as a guide. In that case, Indian Pines is originally an image of 145x145 pixels and 200 bands that is transformed into 10249 patches of 5x5 pixels using the function `createImageCubes`; that is, a single image is converted into a dataset of 10249 samples. Similarly, you only have one image of 1920x1080 pixels and 29 bands, not a dataset per se. The way that an image is transformed into a dataset could be as simple as in the case of Indian Pines, but it most likely depends on your own classification problem. For example, in the case of our [Kochia dataset](https://www.mdpi.com/2072-4292/13/18/3649), we had to convert images of similar dimensions as yours into a dataset of 6316 samples, each of which represented patches of 25x25 pixels (the extraction of the patches can be manual or automatic): 
![image](https://github.com/NISL-MSU/HSI-BandSelection/assets/42776065/92cba0a3-9abf-460d-b5de-19724910b1fa)
